<?php

/**
 * BasePersonDay
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sales_person_id
 * @property integer $day_id
 * @property SalesPerson $SalesPerson
 * @property Day $Day
 * 
 * @method integer     getSalesPersonId()   Returns the current record's "sales_person_id" value
 * @method integer     getDayId()           Returns the current record's "day_id" value
 * @method SalesPerson getSalesPerson()     Returns the current record's "SalesPerson" value
 * @method Day         getDay()             Returns the current record's "Day" value
 * @method PersonDay   setSalesPersonId()   Sets the current record's "sales_person_id" value
 * @method PersonDay   setDayId()           Sets the current record's "day_id" value
 * @method PersonDay   setSalesPerson()     Sets the current record's "SalesPerson" value
 * @method PersonDay   setDay()             Sets the current record's "Day" value
 * 
 * @package    esmya
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePersonDay extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('person_day');
        $this->hasColumn('sales_person_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('day_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SalesPerson', array(
             'local' => 'sales_person_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Day', array(
             'local' => 'day_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}