<?php

/**
 * BaseTarget
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sales_target
 * @property date $time_period
 * @property integer $sales_person_id
 * @property SalesPerson $SalesPerson
 * 
 * @method integer     getSalesTarget()     Returns the current record's "sales_target" value
 * @method date        getTimePeriod()      Returns the current record's "time_period" value
 * @method integer     getSalesPersonId()   Returns the current record's "sales_person_id" value
 * @method SalesPerson getSalesPerson()     Returns the current record's "SalesPerson" value
 * @method Target      setSalesTarget()     Sets the current record's "sales_target" value
 * @method Target      setTimePeriod()      Sets the current record's "time_period" value
 * @method Target      setSalesPersonId()   Sets the current record's "sales_person_id" value
 * @method Target      setSalesPerson()     Sets the current record's "SalesPerson" value
 * 
 * @package    esmya
 * @subpackage model
 * @author     Duncan Watson duncan@duncanwatson.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTarget extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('target');
        $this->hasColumn('sales_target', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('time_period', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('sales_person_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SalesPerson', array(
             'local' => 'sales_person_id',
             'foreign' => 'id'));
    }
}