<?php

/**
 * BaseDay
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $sales_date
 * @property integer $actual_sales
 * @property integer $sales_person_id
 * @property SalesPerson $SalesPerson
 * 
 * @method date        getSalesDate()       Returns the current record's "sales_date" value
 * @method integer     getActualSales()     Returns the current record's "actual_sales" value
 * @method integer     getSalesPersonId()   Returns the current record's "sales_person_id" value
 * @method SalesPerson getSalesPerson()     Returns the current record's "SalesPerson" value
 * @method Day         setSalesDate()       Sets the current record's "sales_date" value
 * @method Day         setActualSales()     Sets the current record's "actual_sales" value
 * @method Day         setSalesPersonId()   Sets the current record's "sales_person_id" value
 * @method Day         setSalesPerson()     Sets the current record's "SalesPerson" value
 * 
 * @package    esmya
 * @subpackage model
 * @author     Duncan Watson duncan@duncanwatson.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDay extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('day');
        $this->hasColumn('sales_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('actual_sales', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sales_person_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SalesPerson', array(
             'local' => 'sales_person_id',
             'foreign' => 'id'));
    }
}