<?php

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $country_id
 * @property Doctrine_Collection $SalePeople
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getCountryId()  Returns the current record's "country_id" value
 * @method Doctrine_Collection getSalePeople() Returns the current record's "SalePeople" collection
 * @method Region              setName()       Sets the current record's "name" value
 * @method Region              setCountryId()  Sets the current record's "country_id" value
 * @method Region              setSalePeople() Sets the current record's "SalePeople" collection
 * 
 * @package    esmya
 * @subpackage model
 * @author     Duncan Watson duncan@duncanwatson.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('region');
        $this->hasColumn('name', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SalesPerson as SalePeople', array(
             'local' => 'id',
             'foreign' => 'region_id'));
    }
}