raceSuccess:
  has_layout: false

aboutTheRaceSuccess:
  has_layout: false

statsSuccess:
  has_layout: false

raceJSONSuccess:
  has_layout: false

leaderBoardSuccess:
  has_layout: false

monthlyRegionalStatsSuccess:
  has_layout: false