<?php

/**
 * Chat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    esmya
 * @subpackage model
 * @author     Duncan Watson duncan@duncanwatson.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Chat extends BaseChat
{
}
