<?php

/**
 * PersonDayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PersonDayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PersonDayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PersonDay');
    }
}