<?php

/**
 * SalesPersonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalesPersonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalesPersonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SalesPerson');
    }
}