<?php

/**
 * TargetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TargetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TargetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Target');
    }

    public function allMyTargets ($user_id) {

        $q = Doctrine_Query::create()
            ->select('*')
            ->from('Target t')
            ->where ('t.sales_person_id = ?', $user_id)
            ->orderBy('t.time_period DESC')
            ->execute();

        return $q;
    }

}