# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# this is the individual salespeople

leaderboard:
  url:   /leaderboard
  param: { module: present, action: leaderBoard }

stats:
  url:   /stats
  param: { module: present, action: stats }

monthly_stats_data:
  url:   /monthly_stats
  param: { module: present, action: monthlyIndividualStats }

# this is the monthly regionals

monthly_regional_stats:
  url:   /regional_stats
  param: { module: present, action: monthlyRegionalStats }

monthly_regional_stats_data:
  url:   /regional_stats_data
  param: { module: present, action: monthlyRegionalStatsData }



chart_data:
  url:   /chart_data
  param: { module: present, action: chartData }

race:
  url:   /race
  param: { module: present, action: race }

raceJSON:
  url:   /race_json
  param: { module: present, action: raceJSON }


people:
  class:   sfDoctrineRouteCollection
  options:
    model:                SalesPerson
    module:               people
    prefix_path:          /people
    column:               id
    with_wildcard_routes: true

sales:
  class:   sfDoctrineRouteCollection
  options:
    model: Day
    module:               sales
    prefix_path:          /sales
    column:               id
    with_wildcard_routes: true

target:
  class:   sfDoctrineRouteCollection
  options:
    model:                Target
    module:               target
    prefix_path:          /targets
    column:               id
    with_wildcard_routes: true



# default rules
homepage:
  url:   /
  param: { module: present, action: race }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
