generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [firstName, lastName, is_active]
        object_actions:
          (D)activate: ~
          _edit: ~
      filter:  ~
      form:
        class: BackendSfGuardUserForm

      edit:    ~
      new:     ~
