SalesPerson:
  columns:
    name:               { type: string (32)}
    region_id:          { type: integer, notnull: true }
    user_id:            { type: integer, notnull: true }
    is_active:          { type: boolean, notnull: true, default: 1 }
    is_admin:           { type: boolean, notnull: true, default: 0 }
  relations:
    Region:             { local: region_id, foreign: id, foreignAlias: SalePeople }
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      type: one
      foreignType: one
      foreignAlias: SalesPerson

Day:
  columns:
    sales_date:         { type: date }
    actual_sales:       { type: integer }
    sales_person_id:    { type: integer, notnull: true }
  relations:
    SalesPerson:        { local: sales_person_id, foreign: id, foreignAlias: Days }

Target:
  columns:
    sales_target:       { type: integer }
    time_period:        { type: date }
    sales_person_id:    { type: integer, notnull: true }
  relations:
    SalesPerson:        { local: sales_person_id, foreign: id, foreignAlias: Targets }

Region:
  columns:
    name:               { type: string (32)}
    co_code:            { type: string (2)}
    country_id:           { type: integer }

Chat:
  columns:
    sales_person_id:    { type: integer, notnull: true }
    chat_month:         { type: string (12) }
    chat_podium:        { type: integer }
    time_entered:       { type: date }
    message:            { type: string (255)}
  relations:
    SalesPerson:        { local: sales_person_id, foreign: id, foreignAlias: Chats }


